---
title: "Beta_Diversity_PD_Final_Version"
output: html_document
date: "2026-04-15"
---

```{r libraries, include=FALSE}

library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)
library(microbiome)
library(indicspecies)
library(writexl)
library(tibble)
library(ggplot2)
```

## Load the data

```{r load_data}

metadata = read.delim('parkinsons_metadata.txt', row.names = 1) 
taxonomy = read.delim('taxonomy.tsv', row.names = 1) 
counts = read.delim('feature-table.txt', skip=1, row.names=1)  
```

# Beta Diversity Analysis

```{r}

# Wrangle Taxonomy Table
taxonomy_formatted <- taxonomy %>%
  separate(col = Taxon,
           into = c('Domain', 'Phylum', 'Class', 'Order', 'Family', 
                               'Genus', 'Species'),
           sep = ';', fill = 'right') %>%
  select(-Confidence) %>%
  as.matrix()

# Wrangle Counts Table
counts_formatted <- counts %>% as.matrix()

# Wrangle Metadata Table:
# Extract Column Names
meta_names <- read.delim('parkinsons_metadata.txt', row.names = 1) %>% names()

# Extract Data
meta_data <- read.delim('parkinsons_metadata.txt', row.names = 1, skip = 1, header = F)

# Set column names for metadata
names(meta_data) = meta_names

# Creating the phyloseq object
# Note - phyloseq object is also created for alpha diversity analysis - this is highly similar, with minor differences. All downstream analyses use the alpha diversity phyloseq object! 
ps = phyloseq(sample_data(meta_data),
               otu_table(counts_formatted, taxa_are_rows = T),
               tax_table(taxonomy_formatted))

# Filter for Parkinson's Disease only
ps_PD <- subset_samples(ps, Disease == "PD")

# Remove taxa that are now zero after subsetting
ps_PD <- prune_taxa(taxa_sums(ps_PD) > 0, ps_PD)

# Visualize sequencing depth
hist(sample_sums(ps_PD))

# Rarefaction curves
rarecurve(t(data.frame(ps@otu_table)),
          step = 500)

# Rarefying phyloseq object
set.seed(13)
psrare <- rarefy_even_depth(ps_PD, sample.size = 5103, rngseed = 13)

table(sample_sums(psrare))

ps_bray <- phyloseq::distance(psrare, method = "bray")

mds <- metaMDS(ps_bray)

# Extract NMDS coordinates
mds_data <- as.data.frame(mds$points)
mds_data$SampleID <- rownames(mds_data)

# Merge metadata
metadata <- sample_data(psrare) %>%
  data.frame() %>%
  rownames_to_column("SampleID")

mds_data <- merge(mds_data, metadata, by = "SampleID")

# Generating beta diversity ordination 
beta_plot <- ggplot(mds_data,
                    aes(x = MDS1, y = MDS2,
                        colour = Lived_on_farm)) +
  geom_point(size = 3, alpha = 0.9) +
  stat_ellipse(type = "t") +
  theme_classic(base_size = 20) +
  labs(colour = "Lived on Farm") +
    scale_colour_manual(values = c("No" = "darkgrey", "Yes" = "steelblue")) +
  theme(plot.title = element_text(hjust = 0.5))
beta_plot

# ggsave(filename = "beta_plot.png", plot = beta_plot, width = 7, height = 4)

# PERMANOVA testing 
stats_univar <- adonis2(ps_bray ~ Lived_on_farm,
                        data = metadata,
                        permutations = 999)
stats_univar

```

\`\`\`{r}
